<!-- Vertical form options -->
<div class="container-fluid">
  <form class="collection-report-form" method="POST" autocomplete="nope">
    <div class="row">
      <div class="col-md-12" style="padding-left: 12px;margin-top: 13px;">
        <div class="card h-95">
          <div class="card-header d-flex bg-transparent border-bottom" style="padding-top: 12px;padding-right: 1px;padding-bottom:10px;">
              <!-- Generated by -->
              <input type="hidden" name="tns-generatedby" id="tns-generatedby" value="<?php echo $_SESSION["empid"];?>">

              <h4 class="card-title flex-grow-1 transaction-name">COLLECTION REPORT</h4>              

              <div class="col-sm-4 form-group" style="padding: 0px;padding-top:8px;margin:0;">
              </div>              

              <div class="col-sm-2 form-group" style="padding: 0px;padding-top:8px;padding-left:7px;margin:0;">
                <button type="button" class="btn btn-light" disabled name="btn-print-report" id="btn-print-report" style="float:right;margin-right:19px;"><i class="icon-printer"></i>&nbsp;&nbsp;Print</button>
                <button type="button" class="btn btn-light" disabled name="btn-export" id="btn-export" style="float:right;margin-right:19px;"><i class="icon-file-spreadsheet"></i>&nbsp;&nbsp;Export</button>
              </div>    
          </div>

          <div class="card-body" style="padding-bottom: 0;margin: 0;padding-top: 5px;">
              <div class="row" style="padding: 0;margin-bottom: 0;">
                <div class="col-sm-4 form-group">
                  <label>REPORT TYPE</label>
                  <select data-placeholder="< Select Type >" class="form-control select" data-container-css-class="bg-indigo-400" data-fouc id="lst-reptype" name="lst-reptype" required>
                    <option></option>
                    <optgroup label="AR PAYMENT COLLECTION">
                        <option value="1">Collection Summary</option>
                        <option value="2">Collection Details</option>
                        <option value="3">Collection Invoice Posting</option>
                    <optgroup label="OVERALL COLLECTION">   
                        <option value="4">Daily Collection Series</option>
                        <option value="5">Monthly Collection Series</option>
                    <!-- <optgroup label="SYNTHESIZED SYNOPSIS REPORT">   
                        <option value="6">Collection + Credit Sequence</option>   
                        <option value="7">Branch Collection + Credit Summary</option> 
                    <optgroup label="EXTRAPOLATED REPORT">   
                        <option value="8">Unified Comprehensive Sales + Collection</option>   
                        <option value="9">Branch Unified Sales + Collection</option>     -->
                  </select>
                </div> 

                <div class="col-sm-3 form-group">
                  <div class="form-group">
                    <label>Date Range</label>
                    <div class="input-group">
                      <span class="input-group-prepend">
                        <span class="input-group-text"><i class="icon-calendar22"></i></span>
                      </span>
                      <input type="text" class="form-control daterange-basic" id="lst_date_range" name="lst_date_range" required> 
                    </div>
                  </div>
                </div>

                <div class="col-sm-3 form-group">
                  <label for="lst-customercode" id="lbl-lst-customercode" style="color:aqua;">= &gt; Customer</label>
                  <select data-placeholder="< Select Customer >" class="form-control select-search" id="lst-customercode" name="lst-customercode" required>
                    <option></option>
                    <?php
                        $customers = (new ControllerClients)->ctrShowCustomerList();
                        foreach ($customers as $key => $value) {
                          echo '<option value="'.$value["customercode"].'">'.$value["name"].'</option>';
                        }
                    ?>
                  </select>              
                </div>

                <div class="col-sm-2 form-group">
                  <label for="lst-paymode" id="lbl-lst-paymode" style="color:aqua;">= &gt; Mode</label>
                  <select data-placeholder="< Select Mode >" class="form-control select" data-fouc id="lst-paymode" name="lst-paymode" required>
                    <option></option>
                    <option value="Cash">Cash</option>
                    <option value="Check">Check</option>
                  </select>
                </div>            

              </div>                                        
          </div>  <!-- card body -->

          <hr style="margin:0;padding: 0;padding-bottom: 24px;">

          <div class="row collection_content" id="collection_content" style="min-height:62vh;padding-left:20px;padding-right:20px;">
          </div> 
          
          <div class="card-footer" style="padding-top: 0;margin-top: 0;">
          </div>  <!-- footer -->
       </div>     <!-- card -->
      </div>

    </div>  <!-- row -->
  </form>
</div>

<script src="views/js/collectionreport.js"></script>