<?php
session_start();

date_default_timezone_set('Asia/Manila');

require_once "../../../controllers/collectionreport.controller.php";
require_once "../../../models/collectionreport.model.php";

require_once "../../../controllers/employees.controller.php";
require_once "../../../models/employees.model.php";

class printCollection{
 public $start_date;
 public $end_date;
 public $customercode;
 public $paymode;
 public $reptype;
 public $generatedby;

public function getCollectionDetails(){
  $field = "empid";
  $empid = $this->generatedby;
  $employee = (new ControllerEmployees)->ctrShowEmployees($field, $empid);
  if ($employee['mi'] != ''){
    $generated_by = $employee['fname'].' '.$employee['mi'].'. '.$employee['lname'];  
  }else{
    $generated_by = $employee['fname'].' '.$employee['lname'];
  }

  $start_date = $this->start_date;
  $end_date = $this->end_date;
  $customercode = $this->customercode;
  $paymode = $this->paymode;
  $reptype = $this->reptype;

  $startdate = substr($start_date,5,2)."/".substr($start_date,8,2)."/".substr($start_date,0,4);
  $enddate = substr($end_date,5,2)."/".substr($end_date,8,2)."/".substr($end_date,0,4);

  if ($startdate != $enddate){
    $trans_date = $startdate . ' - ' . $enddate;
  }else{
    $trans_date = $startdate;
  }

  $current_date = date("m/d/Y");

  $collection = (new ControllerCollection)->ctrShowCollectionReport($start_date, $end_date, $customercode, $paymode, $reptype);
  $nRec = count($collection); 

  require_once('tcpdf_include.php');
  $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
  $pdf->startPageGroup();
  $pdf->setPrintHeader(false);	/*remove line on top of the page*/
  // $pdf->SetLeftMargin(20);
  // $pdf->AddPage();

  // $pdf->AddPage('L', 'LEGAL');

// ================================================================
//                         COLLECTION SUMMARY
// ================================================================ 
  if ($reptype == 1){
    $pdf->AddPage();   /*short-size portrait*/
    $header = <<<EOF
    <table>
      <tr>
        <td style="width:540px;text-align:center;font-size:1.2em;font-weight:bold;">BACOLOD LUIS PAINT CENTER</td> 
      </tr>

      <tr>
        <td style="width:540px;text-align:center;font-size:8px;">Capitol Shopping Center, Tindalo Ave., Brgy. Villamonte</td> 
      </tr>  

      <tr>
        <td style="width:540px;text-align:center;font-size:1.2em;font-weight:bold;">COLLECTION SUMMARY</td> 
      </tr>   

      <tr>
        <td></td>
      </tr>

      <tr>
        <td colspan="2" style="width:435px;text-align:right;font-size:9px;">Col Date: $trans_date</td>
      </tr>      

      <tr>
        <td style="width:105px;"></td>
        <td style="border: 1px solid #666;width:240px;text-align:left;font-size:10px;">&nbsp;&nbsp;&nbsp;Customer</td>                               
        <td style="border: 1px solid #680;width:90px;text-align:right;font-size:10px;">Amount &nbsp;&nbsp;&nbsp;</td>            
      </tr>                   
    </table>
EOF;
    $pdf->writeHTML($header, false, false, false, false, '');

// ------------------------------------------------------------
  $total = 0.00;  
  foreach ($collection as $key => $value) {
    $name = $value["name"];
    $amount = number_format($value["amount"],2);
    $total = $total + $value["amount"];
    
      $content = <<<EOF
      <table style="border: none;">    
        <tr>
          <td style="width:105px;"></td>
          <td style="width:230px;text-align:left;font-size:10px;">&nbsp;&nbsp;$name</td>                          
          <td style="width:100px;text-align:right;font-size:10px;">$amount&nbsp;&nbsp;</td>             
        </tr>                 
      </table>
EOF;
      $pdf->writeHTML($content, false, false, false, false, '');      
    }     
    $total_amount = number_format($total,2);
    if ($nRec > 0){
        $total = <<<EOF
        <table style="border: none;">    
          <tr>
            <td style="width:105px;"></td>
            <td style="width:230px;text-align:right;font-size:11px;font-weight:bold;font-size:1em;border-top:1px solid black;border-right:1px solid black;border-bottom:1px solid black;">&nbsp;&nbsp;TOTAL AMOUNT</td>                          
            <td style="width:100px;text-align:right;font-size:11px;font-weight:bold;font-size:1em;border-top:1px solid black;border-bottom:1px solid black;">$total_amount&nbsp;&nbsp;</td>             
          </tr>

          <tr>
            <td></td>
          </tr>

          <tr>
            <td style="width:105px;"></td>
            <td style="width:230px;"></td>
            <td style="width:100px;text-align:left;font-size:9px;">Generated by:</td>                          
          </tr>

          <tr>
            <td></td>
          </tr>

          <tr>
            <td style="width:105px;"></td>
            <td style="width:230px;"></td>
            <td style="width:100px;text-align:left;font-size:9px;">$generated_by</td>                          
          </tr>  

          <tr>
            <td style="width:105px;"></td>
            <td style="width:230px;"></td>
            <td style="width:100px;text-align:left;font-size:9px;">$current_date</td>                          
          </tr>
        </table>
  EOF;
        $pdf->writeHTML($total, false, false, false, false, '');        
    }
  }  //end report-type

// ================================================================
//                         COLLECTION DETAILS
// ================================================================  
  if ($reptype == 2){
  // $pdf->AddPage('L', 'LETTER');
  $pdf->AddPage();   /*short-size portrait*/
  $header = <<<EOF
  <table>
    <tr>
      <td style="width:540px;text-align:center;font-size:1.2em;font-weight:bold;">BACOLOD LUIS PAINT CENTER</td> 
    </tr>

    <tr>
      <td style="width:540px;text-align:center;font-size:8px;">Capitol Shopping Center, Tindalo Ave., Brgy. Villamonte</td> 
    </tr>  

    <tr>
      <td style="width:540px;text-align:center;font-size:1.2em;font-weight:bold;">COLLECTION DETAILS</td> 
    </tr>   

    <tr>
      <td></td>
    </tr>

    <tr>
      <td colspan="2" style="width:533px;text-align:right;font-size:9px;">Col Date: $trans_date</td>
    </tr>

    <tr>                             
      <td style="border: 1px solid black;width:177px;text-align:left;font-size:9px;">&nbsp;&nbsp;Customer</td>
      <td style="border: 1px solid black;width:60px;text-align:left;font-size:9px;">&nbsp;&nbsp;Date Paid</td> 
      <td style="border: 1px solid black;width:40px;text-align:left;font-size:9px;">&nbsp;&nbsp;Mode</td>  
      <td style="border: 1px solid black;width:60px;text-align:right;font-size:9px;">Amount &nbsp;&nbsp;</td> 
      <td style="border: 1px solid black;width:60px;text-align:left;font-size:9px;">&nbsp;&nbsp;&nbsp;Check #</td>
      <td style="border: 1px solid black;width:60px;text-align:left;font-size:9px;">&nbsp;&nbsp;Check Date</td>  
      <td style="border: 1px solid black;width:75px;text-align:left;font-size:9px;">&nbsp;&nbsp;Bank</td>         
    </tr>                   
  </table>
EOF;
  $pdf->writeHTML($header, false, false, false, false, '');
  
  $i = 0;
  foreach ($collection as $key => $value) {
    $name = $value["name"];
    $pay_date = $value["paydate"];
    $paydate = substr($pay_date,5,2)."/".substr($pay_date,8,2)."/".substr($pay_date,0,4);
    $paymode = $value["paymode"];
    $amount = number_format($value["amount"],2);
    $checknum = $value["checknum"];
    $check_date = $value["checkdate"];
    if ($check_date == '0000-00-00'){
      $checkdate = '';
    }else{
      $checkdate = substr($check_date,5,2)."/".substr($check_date,8,2)."/".substr($check_date,0,4);
    }
    $bank = $value["bank"];
    // $total = $total + $value["amount"];

    if ($i == 0){
      $prev_name = $name;
    }else{
      $curr_name = $name;
      if ($prev_name == $curr_name){
        $name = "";
      }
      $prev_name = $curr_name;
    }

    $i = $i + 1;
    
    if ($pay_date != null){
      $content = <<<EOF
      <table style="border: none;">    
        <tr>
          <td style="width:177px;text-align:left;font-size:9px;">&nbsp;$name</td>   
          <td style="width:60px;text-align:left;font-size:9px;">&nbsp;$paydate</td> 
          <td style="width:40px;text-align:left;font-size:9px;">&nbsp;$paymode</td>                        
          <td style="width:60px;text-align:right;font-size:9px;">$amount&nbsp;</td>  
          <td style="width:60px;text-align:right;font-size:9px;">&nbsp;$checknum</td> 
          <td style="width:60px;text-align:right;font-size:9px;">&nbsp;$checkdate</td> 
          <td style="width:75px;text-align:right;font-size:9px;">&nbsp;$bank</td>            
        </tr>                 
      </table>
EOF;
      $pdf->writeHTML($content, false, false, false, false, '');   
    }elseif (($pay_date == null)&&($value["name"]!= null)){
      $content = <<<EOF
      <table style="border: none;">    
        <tr>
          <td style="width:170px;text-align:left;font-size:9px;"></td>   
          <td style="width:60px;text-align:left;font-size:9px;"></td> 
          <td style="width:47px;text-align:left;font-size:9px;"></td>                        
          <td height="17" style="width:60px;text-align:right;font-size:9px;border-top:1px solid black;color:green;">$amount</td>             
          <td style="width:60px;text-align:left;font-size:9px;"></td>
          <td style="width:60px;text-align:left;font-size:9px;"></td>
          <td style="width:75px;text-align:left;font-size:9px;"></td>
        </tr>                 
      </table>
EOF;
      $pdf->writeHTML($content, false, false, false, false, '');        
    }else{
      $content = <<<EOF
      <table style="border: none;">    
        <tr>
          <td style="width:230px;text-align:right;font-size:11px;border-top:1px solid black;font-weight:bold;border-right:1px solid black;border-bottom:1px solid black;">TOTAL AMOUNT</td>                           
          <td style="width:107px;text-align:right;font-size:11px;border-top:1px solid black;color:green;font-weight:bold;border-bottom:1px solid black;">$amount</td>             
          <td style="width:195px;text-align:left;font-size:11px;border-top:1px solid black;border-bottom:1px solid black;"></td>
        </tr>                 
      </table>
EOF;
      $pdf->writeHTML($content, false, false, false, false, '');      
    }   
  }
  
    $footer = <<<EOF
    <table style="border: none;">  
      <tr>
        <td></td>
      </tr>    
    
      <tr>
        <td style="width:103px;"></td>
        <td style="width:330px;"></td>
        <td style="width:100px;text-align:left;font-size:9px;">Generated by:</td>                          
      </tr>

      <tr>
        <td></td>
      </tr>

      <tr>
        <td style="width:103px;"></td>
        <td style="width:330px;"></td>
        <td style="width:100px;text-align:left;font-size:9px;">$generated_by</td>                          
      </tr>  

      <tr>
        <td style="width:103px;"></td>
        <td style="width:330px;"></td>
        <td style="width:100px;text-align:left;font-size:9px;">$current_date</td>                          
      </tr>              
    </table>
  EOF;
    $pdf->writeHTML($footer, false, false, false, false, '');      
  
  

// ------------------------------------------------------------
// $i = 0;  
// foreach ($products as $key => $value) {
//   $i = $i + 1;
//   $prodid = $value["prodid"];
//   $catdescription = $value["catdescription"];
//   $brandname = $value["brandname"];
//   $prodname = $value["prodname"];
//   $prod_name = ($brandname != '') ? $brandname . ' ' . $prodname : $prodname;
//   $ucost = number_format($value["ucost"],2);
//   $markup = number_format($value["uprice"] - $value["ucost"],2);
//   $uprice = number_format($value["uprice"],2);
  
//   if (($user_type == "Super Administrator")||($user_type == "Administrator")){
//     $content = <<<EOF
//     <table style="border: none;">    
//       <tr>  
//         <td style="width:35px;"></td>
//         <td style="border: 1px solid black;width:30px;text-align:center;font-size:9px;">$i</td>                        
//         <td style="width:265px;text-align:left;font-size:9px;">&nbsp;&nbsp;$prod_name</td>
//         <td style="width:60px;text-align:right;font-size:9px;">$ucost &nbsp;</td> 
//         <td style="width:55px;text-align:right;font-size:9px;">$markup &nbsp;</td>
//         <td style="width:60px;text-align:right;font-size:9px;">$uprice &nbsp;</td>            
//       </tr>                 
//     </table>
// EOF;
//     $pdf->writeHTML($content, false, false, false, false, '');
//   }else{
//     $content = <<<EOF
//     <table style="border: none;">    
//       <tr>
//         <td style="width:35px;"></td>
//         <td style="border: 1px solid black;width:30px;text-align:center;font-size:9px;">$i</td>                          
//         <td style="width:265px;text-align:left;font-size:9px;">&nbsp;&nbsp;$prod_name</td>
//         <td style="width:60px;text-align:right;font-size:9px;">$ucost &nbsp;&nbsp;&nbsp;</td> 
//         <td style="width:55px;text-align:right;font-size:9px;">$markup &nbsp;&nbsp;&nbsp;</td>
//         <td style="width:60px;text-align:right;font-size:9px;">$uprice &nbsp;&nbsp;&nbsp;</td>             
//       </tr>                 
//     </table>
// EOF;
//     $pdf->writeHTML($content, false, false, false, false, '');      
//   }       
// } 
  
  }  //end report-type   
  
// ================================================================
//             UNIFIED COMPREHENSIVE SALES + COLLECTION
// ================================================================ 
  if ($reptype == 8){
    $pdf->AddPage('L', 'LEGAL');
    $header = <<<EOF
    <table>
      <tr>
        <td style="width:860px;text-align:center;font-size:1.2em;font-weight:bold;">RFC</td> 
      </tr>

      <tr>
        <td style="width:860px;text-align:center;font-size:10px;">$branch_name</td> 
      </tr>  

      <tr>
        <td style="width:860px;text-align:center;font-size:1.2em;font-weight:bold;">UNIFIED COMPREHENSIVE SALES + COLLECTION</td> 
      </tr>   

      <tr>
        <td></td>
      </tr>

      <tr>
        <td colspan="2" style="width:775px;text-align:right;font-size:9px;">Col Date: $trans_date</td>
      </tr>

      <tr>
        <td style="width:60px;"></td>
        <td colspan="3" style="border: 1px solid black;width:215px;text-align:center;font-size:9px;">CASH SALES</td>
        <td colspan="3" style="border: 1px solid black;width:215px;text-align:center;font-size:9px;">SALES ON ACCOUNT</td>
        <td colspan="4" style="border: 1px solid black;width:285px;text-align:center;font-size:9px;">ACCOUNT RECEIVABLE COLLECTION</td>
      </tr>

      <tr>                             
        <td style="border: 1px solid black;width:60px;text-align:left;font-size:9px;">&nbsp;&nbsp;Date</td>  
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">VAT &nbsp;&nbsp;</td>
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">Non-VAT &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:75px;text-align:right;font-size:9px;">Total &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">VAT &nbsp;&nbsp;</td>
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">Non-VAT &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:75px;text-align:right;font-size:9px;">Total &nbsp;&nbsp;</td>
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">Cash &nbsp;&nbsp;</td>
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">ODC &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">PDC &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:75px;text-align:right;font-size:9px;">Total &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:85px;text-align:right;font-size:9px;">Extension &nbsp;&nbsp;</td>       
      </tr>                   
    </table>
  EOF;
    $pdf->writeHTML($header, false, false, false, false, '');

    $counter_VAT_amount = 0.00;
    $counter_Non_VAT_amount = 0.00;
    $counter_total = 0.00;
    $credit_VAT_amount = 0.00;
    $credit_Non_VAT_amount = 0.00;
    $credit_total = 0.00;
    $cash_amount = 0.00;
    $check_ondate_amount = 0.00;
    $check_post_dated_amount = 0.00;
    $total_amount = 0.00;

    // last row
    $total_VAT_counter = 0.00;
    $total_Non_VAT_counter = 0.00;
    $total_counter = 0.00;

    $total_VAT_credit = 0.00;
    $total_Non_VAT_credit = 0.00;
    $total_credit = 0.00;

    $total_cash = 0.00;
    $total_check_ondate = 0.00;
    $total_check_postdated = 0.00;

    $i = 0;
    foreach ($collection as $key => $value) {
      $col_date = $value["cdate"];
      $cdate = substr($col_date,5,2)."/".substr($col_date,8,2)."/".substr($col_date,0,4);
      $salemode = $value["salemode"];
      $vatdesc = $value["vatdesc"];
      $paymode = $value["paymode"];
      $checkdesc = $value["checkdesc"];
      $amount = $value["amount"];
      // $amount = number_format($value["amount"],2);

      if ($i == 0){
        $prev_date = $cdate;    
        if (($salemode == 'Counter')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
          $counter_VAT_amount = $amount;  
          $counter_total = $counter_total + $amount;    
          // last row
          $total_VAT_counter = $total_VAT_counter + $amount;
          $total_counter = $total_counter + $amount;
        }elseif (($salemode == 'Counter')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
          $counter_Non_VAT_amount = $amount;   
          $counter_total = $counter_total + $amount; 
          // last row
          $total_Non_VAT_counter = $total_VAT_counter + $amount;
          $total_counter = $total_counter + $amount;
        }else if (($salemode == 'Credit')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
          $credit_VAT_amount = $amount; 
          $credit_total = $credit_total + $amount;
          // last row
          $total_VAT_credit = $total_VAT_credit + $amount;     
         $ $total_credit = $total_credit + $amount;  
        }elseif (($salemode == 'Credit')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
          $credit_Non_VAT_amount = $amount;
          $credit_total = $credit_total + $amount;
          // last row
          $total_Non_VAT_credit = $total_Non_VAT_credit + $amount;      
          $total_credit = $total_credit + $amount;  
        }elseif (($salemode == 'Collection')&&($paymode == 'Cash')&&($checkdesc == '')){
          $cash_amount = $amount;
          $total_cash = $total_cash + $amount;
        }elseif (($salemode == 'Collection')&&($paymode == 'Check')&&($checkdesc == 'On-date')){
          $check_ondate_amount = $amount;
          $total_check_ondate = $total_check_ondate + $amount;
        }else{
          $check_post_dated_amount = $amount;
          $total_check_postdated = $total_check_postdated + $amount;
        }
        $total_amount = $total_amount + $amount;    // last column
      }else{
        $curr_date = $cdate;         
        if ($prev_date == $curr_date){
          if (($salemode == 'Counter')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
            $counter_VAT_amount = $amount;  
            $counter_total = $counter_total + $amount;    
            // last row
            $total_VAT_counter = $total_VAT_counter + $amount;
            $total_counter = $total_counter + $amount;
          }elseif (($salemode == 'Counter')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
            $counter_Non_VAT_amount = $amount;   
            $counter_total = $counter_total + $amount; 
            // last row
            $total_Non_VAT_counter = $total_VAT_counter + $amount;
            $total_counter = $total_counter + $amount;
          }else if (($salemode == 'Credit')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
            $credit_VAT_amount = $amount; 
            $credit_total = $credit_total + $amount;
            // last row
            $total_VAT_credit = $total_VAT_credit + $amount;     
           $ $total_credit = $total_credit + $amount;  
          }elseif (($salemode == 'Credit')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
            $credit_Non_VAT_amount = $amount;
            $credit_total = $credit_total + $amount;
            // last row
            $total_Non_VAT_credit = $total_Non_VAT_credit + $amount;      
            $total_credit = $total_credit + $amount;  
          }elseif (($salemode == 'Collection')&&($paymode == 'Cash')&&($checkdesc == '')){
            $cash_amount = $amount;
            $total_cash = $total_cash + $amount;
          }elseif (($salemode == 'Collection')&&($paymode == 'Check')&&($checkdesc == 'On-date')){
            $check_ondate_amount = $amount;
            $total_check_ondate = $total_check_ondate + $amount;
          }else{
            $check_post_dated_amount = $amount;
            $total_check_postdated = $total_check_postdated + $amount;
          }
          $total_amount = $total_amount + $amount;    // last column
        }else{
          // Formatted with comma before printing
          $_counter_VAT_amount = number_format($counter_VAT_amount,2);
          $_counter_Non_VAT_amount = number_format($counter_Non_VAT_amount,2);
          $_counter_total = number_format($counter_total,2);
          $_credit_VAT_amount = number_format($credit_VAT_amount,2);
          $_credit_Non_VAT_amount = number_format($credit_Non_VAT_amount,2);
          $_credit_total = number_format($credit_total,2);
          $_cash_amount = number_format($cash_amount,2);
          $_check_ondate_amount = number_format($check_ondate_amount,2);
          $_check_post_dated_amount = number_format($check_post_dated_amount,2);
          $_total_collection = number_format($cash_amount + $check_ondate_amount + $check_post_dated_amount,2);
          $_total_amount = number_format($total_amount,2);

          $content = <<<EOF
          <table style="border: none;">    
            <tr>
              <td style="width:60px;text-align:left;font-size:9px;border-right:1px solid black;">$prev_date</td>   
              <td style="width:70px;text-align:right;font-size:9px;">$_counter_VAT_amount</td> 
              <td style="width:70px;text-align:right;font-size:9px;">$_counter_Non_VAT_amount</td>
              <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;">$_counter_total</td>
              <td style="width:70px;text-align:right;font-size:9px;">$_credit_VAT_amount</td> 
              <td style="width:70px;text-align:right;font-size:9px;">$_credit_Non_VAT_amount</td>
              <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;">$_credit_total</td>
              <td style="width:70px;text-align:right;font-size:9px;">$_cash_amount</td> 
              <td style="width:70px;text-align:right;font-size:9px;">$_check_ondate_amount</td>
              <td style="width:70px;text-align:right;font-size:9px;">$_check_post_dated_amount</td>
              <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;">$_total_collection</td>
              <td style="width:85px;text-align:right;font-size:9px;">$_total_amount</td>
            </tr>                 
          </table>
    EOF;
          $pdf->writeHTML($content, false, false, false, false, '');

          $counter_VAT_amount = 0.00;
          $counter_Non_VAT_amount = 0.00;
          $counter_total = 0.00;
          $credit_VAT_amount = 0.00;
          $credit_Non_VAT_amount = 0.00;
          $credit_total = 0.00;
          $cash_amount = 0.00;
          $check_ondate_amount = 0.00;
          $check_post_dated_amount = 0.00;
          $total_amount = 0.00;

          if (($salemode == 'Counter')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
            $counter_VAT_amount = $amount;  
            $counter_total = $counter_total + $amount;    
            // last row
            $total_VAT_counter = $total_VAT_counter + $amount;
            $total_counter = $total_counter + $amount;
          }elseif (($salemode == 'Counter')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
            $counter_Non_VAT_amount = $amount;   
            $counter_total = $counter_total + $amount; 
            // last row
            $total_Non_VAT_counter = $total_VAT_counter + $amount;
            $total_counter = $total_counter + $amount;
          }else if (($salemode == 'Credit')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
            $credit_VAT_amount = $amount; 
            $credit_total = $credit_total + $amount;
            // last row
            $total_VAT_credit = $total_VAT_credit + $amount;     
           $ $total_credit = $total_credit + $amount;  
          }elseif (($salemode == 'Credit')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
            $credit_Non_VAT_amount = $amount;
            $credit_total = $credit_total + $amount;
            // last row
            $total_Non_VAT_credit = $total_Non_VAT_credit + $amount;      
            $total_credit = $total_credit + $amount;  
          }elseif (($salemode == 'Collection')&&($paymode == 'Cash')&&($checkdesc == '')){
            $cash_amount = $amount;
            $total_cash = $total_cash + $amount;
          }elseif (($salemode == 'Collection')&&($paymode == 'Check')&&($checkdesc == 'On-date')){
            $check_ondate_amount = $amount;
            $total_check_ondate = $total_check_ondate + $amount;
          }else{
            $check_post_dated_amount = $amount;
            $total_check_postdated = $total_check_postdated + $amount;
          }
          $total_amount = $total_amount + $amount;    // last column
          $prev_date = $curr_date;
        }
      }

      $i = $i + 1;
    }
    if ($i > 0){
      // Formatted with comma before printing
      $_counter_VAT_amount = number_format($counter_VAT_amount,2);
      $_counter_Non_VAT_amount = number_format($counter_Non_VAT_amount,2);
      $_counter_total = number_format($counter_total,2);
      $_credit_VAT_amount = number_format($credit_VAT_amount,2);
      $_credit_Non_VAT_amount = number_format($credit_Non_VAT_amount,2);
      $_credit_total = number_format($credit_total,2);
      $_cash_amount = number_format($cash_amount,2);
      $_check_ondate_amount = number_format($check_ondate_amount,2);
      $_check_post_dated_amount = number_format($check_post_dated_amount,2);
      $_total_collection = number_format($cash_amount + $check_ondate_amount + $check_post_dated_amount,2);
      $_total_amount = number_format($total_amount,2);

      $content = <<<EOF
      <table style="border: none;">    
        <tr>
          <td style="width:60px;text-align:left;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;">$cdate</td>   
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_counter_VAT_amount</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_counter_Non_VAT_amount</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;">$_counter_total</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_credit_VAT_amount</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_credit_Non_VAT_amount</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;">$_credit_total</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_cash_amount</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_check_ondate_amount</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_check_post_dated_amount</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;">$_total_collection</td>
          <td style="width:85px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_amount</td>
        </tr>                 
      </table>
    EOF;
        $pdf->writeHTML($content, false, false, false, false, '');
        
      $_total_VAT_counter = number_format($total_VAT_counter,2);
      $_total_Non_VAT_counter = number_format($total_Non_VAT_counter,2);  
      $_total_counter = number_format($total_counter,2);
      $_total_VAT_credit = number_format($total_VAT_credit,2);
      $_total_Non_VAT_credit = number_format($total_Non_VAT_credit,2);  
      $_total_credit = number_format($total_VAT_credit + $total_Non_VAT_credit,2);
      $_total_cash = number_format($total_cash,2);
      $_total_check_ondate = number_format($total_check_ondate,2);
      $_total_check_postdated = number_format($total_check_postdated,2);
      $_total_overall_collection = number_format($total_cash + $total_check_ondate + $total_check_postdated,2);
      $_overall_summation = number_format($total_counter + $total_VAT_credit + $total_Non_VAT_credit + $total_cash + $total_check_ondate + $total_check_postdated,2);

      $content = <<<EOF
      <table style="border: none;">    
        <tr>
          <td style="width:60px;text-align:left;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;">OVERALL</td>   
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_VAT_counter</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_Non_VAT_counter</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;font-weight:bold;color:indigo;">$_total_counter</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_VAT_credit</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_Non_VAT_credit</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;font-weight:bold;color:indigo;">$_total_credit</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_cash</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_check_ondate</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_check_postdated</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;font-weight:bold;color:indigo;">$_total_overall_collection</td>
          <td style="width:85px;text-align:right;font-size:9px;border-bottom:1px solid black;font-weight:bold;color:forestgreen;">$_overall_summation</td>
        </tr>                 
      </table>
    EOF;
        $pdf->writeHTML($content, false, false, false, false, '');
    }

    $footer = <<<EOF
    <table style="border: none;">  
      <tr>
        <td></td>
      </tr>    
    
      <tr>
        <td style="width:423px;"></td>
        <td style="width:330px;"></td>
        <td style="width:100px;text-align:left;font-size:9px;">Generated by:</td>                          
      </tr>

      <tr>
        <td></td>
      </tr>

      <tr>
        <td style="width:423px;"></td>
        <td style="width:330px;"></td>
        <td style="width:100px;text-align:left;font-size:9px;">$generated_by</td>                          
      </tr>  

      <tr>
        <td style="width:423px;"></td>
        <td style="width:330px;"></td>
        <td style="width:100px;text-align:left;font-size:9px;">$current_date</td>                          
      </tr>              
    </table>
  EOF;
    $pdf->writeHTML($footer, false, false, false, false, '');  
  }

// ================================================================
//                BRANCH UNIFIED SALES + COLLECTION
// ================================================================  
  if ($reptype == 9){
    $pdf->AddPage('L', 'LEGAL');
    $header = <<<EOF
    <table>
      <tr>
        <td style="width:860px;text-align:center;font-size:1.2em;font-weight:bold;">RFC</td> 
      </tr>

      <tr>
        <td style="width:860px;text-align:center;font-size:10px;">$branch_name</td> 
      </tr>  

      <tr>
        <td style="width:860px;text-align:center;font-size:1.2em;font-weight:bold;">BRANCH UNIFIED SALES + COLLECTION</td> 
      </tr>   

      <tr>
        <td></td>
      </tr>

      <tr>
        <td colspan="2" style="width:775px;text-align:right;font-size:9px;">Col Date: $trans_date</td>
      </tr>

      <tr>
        <td style="width:60px;"></td>
        <td colspan="3" style="border: 1px solid black;width:215px;text-align:center;font-size:9px;">CASH SALES</td>
        <td colspan="3" style="border: 1px solid black;width:215px;text-align:center;font-size:9px;">SALES ON ACCOUNT</td>
        <td colspan="4" style="border: 1px solid black;width:285px;text-align:center;font-size:9px;">ACCOUNT RECEIVABLE COLLECTION</td>
      </tr>

      <tr>                             
        <td style="border: 1px solid black;width:60px;text-align:left;font-size:9px;">&nbsp;&nbsp;Branch</td>  
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">VAT &nbsp;&nbsp;</td>
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">Non-VAT &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:75px;text-align:right;font-size:9px;">Total &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">VAT &nbsp;&nbsp;</td>
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">Non-VAT &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:75px;text-align:right;font-size:9px;">Total &nbsp;&nbsp;</td>
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">Cash &nbsp;&nbsp;</td>
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">ODC &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:70px;text-align:right;font-size:9px;">PDC &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:75px;text-align:right;font-size:9px;">Total &nbsp;&nbsp;</td> 
        <td style="border: 1px solid black;width:85px;text-align:right;font-size:9px;">Extension &nbsp;&nbsp;</td>       
      </tr>                   
    </table>
  EOF;
    $pdf->writeHTML($header, false, false, false, false, '');

    $counter_VAT_amount = 0.00;
    $counter_Non_VAT_amount = 0.00;
    $counter_total = 0.00;
    $credit_VAT_amount = 0.00;
    $credit_Non_VAT_amount = 0.00;
    $credit_total = 0.00;
    $cash_amount = 0.00;
    $check_ondate_amount = 0.00;
    $check_post_dated_amount = 0.00;
    $total_amount = 0.00;

    // last row
    $total_VAT_counter = 0.00;
    $total_Non_VAT_counter = 0.00;
    $total_counter = 0.00;

    $total_VAT_credit = 0.00;
    $total_Non_VAT_credit = 0.00;
    $total_credit = 0.00;

    $total_cash = 0.00;
    $total_check_ondate = 0.00;
    $total_check_postdated = 0.00;

    $i = 0;
    foreach ($collection as $key => $value) {
      $branch_name = $value["branch_name"];
      $salemode = $value["salemode"];
      $vatdesc = $value["vatdesc"];
      $paymode = $value["paymode"];
      $checkdesc = $value["checkdesc"];
      $amount = $value["amount"];
      // $amount = number_format($value["amount"],2);

      if ($i == 0){
        $prev_branch = $branch_name;    
        if (($salemode == 'Counter')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
          $counter_VAT_amount = $amount;  
          $counter_total = $counter_total + $amount;    
          // last row
          $total_VAT_counter = $total_VAT_counter + $amount;
          $total_counter = $total_counter + $amount;
        }elseif (($salemode == 'Counter')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
          $counter_Non_VAT_amount = $amount;   
          $counter_total = $counter_total + $amount; 
          // last row
          $total_Non_VAT_counter = $total_VAT_counter + $amount;
          $total_counter = $total_counter + $amount;
        }else if (($salemode == 'Credit')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
          $credit_VAT_amount = $amount; 
          $credit_total = $credit_total + $amount;
          // last row
          $total_VAT_credit = $total_VAT_credit + $amount;     
        $ $total_credit = $total_credit + $amount;  
        }elseif (($salemode == 'Credit')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
          $credit_Non_VAT_amount = $amount;
          $credit_total = $credit_total + $amount;
          // last row
          $total_Non_VAT_credit = $total_Non_VAT_credit + $amount;      
          $total_credit = $total_credit + $amount;  
        }elseif (($salemode == 'Collection')&&($paymode == 'Cash')&&($checkdesc == '')){
          $cash_amount = $amount;
          $total_cash = $total_cash + $amount;
        }elseif (($salemode == 'Collection')&&($paymode == 'Check')&&($checkdesc == 'On-date')){
          $check_ondate_amount = $amount;
          $total_check_ondate = $total_check_ondate + $amount;
        }else{
          $check_post_dated_amount = $amount;
          $total_check_postdated = $total_check_postdated + $amount;
        }
        $total_amount = $total_amount + $amount;    // last column
      }else{
        $curr_branch = $branch_name;         
        if ($prev_branch == $curr_branch){
          if (($salemode == 'Counter')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
            $counter_VAT_amount = $amount;  
            $counter_total = $counter_total + $amount;    
            // last row
            $total_VAT_counter = $total_VAT_counter + $amount;
            $total_counter = $total_counter + $amount;
          }elseif (($salemode == 'Counter')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
            $counter_Non_VAT_amount = $amount;   
            $counter_total = $counter_total + $amount; 
            // last row
            $total_Non_VAT_counter = $total_VAT_counter + $amount;
            $total_counter = $total_counter + $amount;
          }else if (($salemode == 'Credit')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
            $credit_VAT_amount = $amount; 
            $credit_total = $credit_total + $amount;
            // last row
            $total_VAT_credit = $total_VAT_credit + $amount;     
          $ $total_credit = $total_credit + $amount;  
          }elseif (($salemode == 'Credit')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
            $credit_Non_VAT_amount = $amount;
            $credit_total = $credit_total + $amount;
            // last row
            $total_Non_VAT_credit = $total_Non_VAT_credit + $amount;      
            $total_credit = $total_credit + $amount;  
          }elseif (($salemode == 'Collection')&&($paymode == 'Cash')&&($checkdesc == '')){
            $cash_amount = $amount;
            $total_cash = $total_cash + $amount;
          }elseif (($salemode == 'Collection')&&($paymode == 'Check')&&($checkdesc == 'On-date')){
            $check_ondate_amount = $amount;
            $total_check_ondate = $total_check_ondate + $amount;
          }else{
            $check_post_dated_amount = $amount;
            $total_check_postdated = $total_check_postdated + $amount;
          }
          $total_amount = $total_amount + $amount;    // last column
        }else{
          // Formatted with comma before printing
          $_counter_VAT_amount = number_format($counter_VAT_amount,2);
          $_counter_Non_VAT_amount = number_format($counter_Non_VAT_amount,2);
          $_counter_total = number_format($counter_total,2);
          $_credit_VAT_amount = number_format($credit_VAT_amount,2);
          $_credit_Non_VAT_amount = number_format($credit_Non_VAT_amount,2);
          $_credit_total = number_format($credit_total,2);
          $_cash_amount = number_format($cash_amount,2);
          $_check_ondate_amount = number_format($check_ondate_amount,2);
          $_check_post_dated_amount = number_format($check_post_dated_amount,2);
          $_total_collection = number_format($cash_amount + $check_ondate_amount + $check_post_dated_amount,2);
          $_total_amount = number_format($total_amount,2);

          $content = <<<EOF
          <table style="border: none;">    
            <tr>
              <td style="width:60px;text-align:left;font-size:9px;border-right:1px solid black;">$prev_branch</td>   
              <td style="width:70px;text-align:right;font-size:9px;">$_counter_VAT_amount</td> 
              <td style="width:70px;text-align:right;font-size:9px;">$_counter_Non_VAT_amount</td>
              <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;">$_counter_total</td>
              <td style="width:70px;text-align:right;font-size:9px;">$_credit_VAT_amount</td> 
              <td style="width:70px;text-align:right;font-size:9px;">$_credit_Non_VAT_amount</td>
              <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;">$_credit_total</td>
              <td style="width:70px;text-align:right;font-size:9px;">$_cash_amount</td> 
              <td style="width:70px;text-align:right;font-size:9px;">$_check_ondate_amount</td>
              <td style="width:70px;text-align:right;font-size:9px;">$_check_post_dated_amount</td>
              <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;">$_total_collection</td>
              <td style="width:85px;text-align:right;font-size:9px;">$_total_amount</td>
            </tr>                 
          </table>
    EOF;
          $pdf->writeHTML($content, false, false, false, false, '');

          $counter_VAT_amount = 0.00;
          $counter_Non_VAT_amount = 0.00;
          $counter_total = 0.00;
          $credit_VAT_amount = 0.00;
          $credit_Non_VAT_amount = 0.00;
          $credit_total = 0.00;
          $cash_amount = 0.00;
          $check_ondate_amount = 0.00;
          $check_post_dated_amount = 0.00;
          $total_amount = 0.00;

          if (($salemode == 'Counter')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
            $counter_VAT_amount = $amount;  
            $counter_total = $counter_total + $amount;    
            // last row
            $total_VAT_counter = $total_VAT_counter + $amount;
            $total_counter = $total_counter + $amount;
          }elseif (($salemode == 'Counter')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
            $counter_Non_VAT_amount = $amount;   
            $counter_total = $counter_total + $amount; 
            // last row
            $total_Non_VAT_counter = $total_VAT_counter + $amount;
            $total_counter = $total_counter + $amount;
          }else if (($salemode == 'Credit')&&($vatdesc == 'VAT')&&($paymode == '')&&($checkdesc == '')){
            $credit_VAT_amount = $amount; 
            $credit_total = $credit_total + $amount;
            // last row
            $total_VAT_credit = $total_VAT_credit + $amount;     
          $ $total_credit = $total_credit + $amount;  
          }elseif (($salemode == 'Credit')&&($vatdesc == 'Non-VAT')&&($paymode == '')&&($checkdesc == '')){
            $credit_Non_VAT_amount = $amount;
            $credit_total = $credit_total + $amount;
            // last row
            $total_Non_VAT_credit = $total_Non_VAT_credit + $amount;      
            $total_credit = $total_credit + $amount;  
          }elseif (($salemode == 'Collection')&&($paymode == 'Cash')&&($checkdesc == '')){
            $cash_amount = $amount;
            $total_cash = $total_cash + $amount;
          }elseif (($salemode == 'Collection')&&($paymode == 'Check')&&($checkdesc == 'On-date')){
            $check_ondate_amount = $amount;
            $total_check_ondate = $total_check_ondate + $amount;
          }else{
            $check_post_dated_amount = $amount;
            $total_check_postdated = $total_check_postdated + $amount;
          }
          $total_amount = $total_amount + $amount;    // last column
          $prev_branch = $curr_branch;
        }
      }

      $i = $i + 1;
    }
    if ($i > 0){
      // Formatted with comma before printing
      $_counter_VAT_amount = number_format($counter_VAT_amount,2);
      $_counter_Non_VAT_amount = number_format($counter_Non_VAT_amount,2);
      $_counter_total = number_format($counter_total,2);
      $_credit_VAT_amount = number_format($credit_VAT_amount,2);
      $_credit_Non_VAT_amount = number_format($credit_Non_VAT_amount,2);
      $_credit_total = number_format($credit_total,2);
      $_cash_amount = number_format($cash_amount,2);
      $_check_ondate_amount = number_format($check_ondate_amount,2);
      $_check_post_dated_amount = number_format($check_post_dated_amount,2);
      $_total_collection = number_format($cash_amount + $check_ondate_amount + $check_post_dated_amount,2);
      $_total_amount = number_format($total_amount,2);

      $content = <<<EOF
      <table style="border: none;">    
        <tr>
          <td style="width:60px;text-align:left;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;">$branch_name</td>   
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_counter_VAT_amount</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_counter_Non_VAT_amount</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;">$_counter_total</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_credit_VAT_amount</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_credit_Non_VAT_amount</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;">$_credit_total</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_cash_amount</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_check_ondate_amount</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_check_post_dated_amount</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;">$_total_collection</td>
          <td style="width:85px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_amount</td>
        </tr>                 
      </table>
    EOF;
        $pdf->writeHTML($content, false, false, false, false, '');
        
      $_total_VAT_counter = number_format($total_VAT_counter,2);
      $_total_Non_VAT_counter = number_format($total_Non_VAT_counter,2);  
      $_total_counter = number_format($total_counter,2);
      $_total_VAT_credit = number_format($total_VAT_credit,2);
      $_total_Non_VAT_credit = number_format($total_Non_VAT_credit,2);  
      $_total_credit = number_format($total_VAT_credit + $total_Non_VAT_credit,2);
      $_total_cash = number_format($total_cash,2);
      $_total_check_ondate = number_format($total_check_ondate,2);
      $_total_check_postdated = number_format($total_check_postdated,2);
      $_total_overall_collection = number_format($total_cash + $total_check_ondate + $total_check_postdated,2);
      $_overall_summation = number_format($total_counter + $total_VAT_credit + $total_Non_VAT_credit + $total_cash + $total_check_ondate + $total_check_postdated,2);

      $content = <<<EOF
      <table style="border: none;">    
        <tr>
          <td style="width:60px;text-align:left;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;">OVERALL</td>   
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_VAT_counter</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_Non_VAT_counter</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;font-weight:bold;color:indigo;">$_total_counter</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_VAT_credit</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_Non_VAT_credit</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;font-weight:bold;color:indigo;">$_total_credit</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_cash</td> 
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_check_ondate</td>
          <td style="width:70px;text-align:right;font-size:9px;border-bottom:1px solid black;">$_total_check_postdated</td>
          <td style="width:75px;text-align:right;font-size:9px;border-right:1px solid black;border-bottom:1px solid black;font-weight:bold;color:indigo;">$_total_overall_collection</td>
          <td style="width:85px;text-align:right;font-size:9px;border-bottom:1px solid black;font-weight:bold;color:forestgreen;">$_overall_summation</td>
        </tr>                 
      </table>
    EOF;
        $pdf->writeHTML($content, false, false, false, false, '');
    }

    $footer = <<<EOF
    <table style="border: none;">  
      <tr>
        <td></td>
      </tr>    
    
      <tr>
        <td style="width:423px;"></td>
        <td style="width:330px;"></td>
        <td style="width:100px;text-align:left;font-size:9px;">Generated by:</td>                          
      </tr>

      <tr>
        <td></td>
      </tr>

      <tr>
        <td style="width:423px;"></td>
        <td style="width:330px;"></td>
        <td style="width:100px;text-align:left;font-size:9px;">$generated_by</td>                          
      </tr>  

      <tr>
        <td style="width:423px;"></td>
        <td style="width:330px;"></td>
        <td style="width:100px;text-align:left;font-size:9px;">$current_date</td>                          
      </tr>              
    </table>
  EOF;
    $pdf->writeHTML($footer, false, false, false, false, '');  
  }





    $pdf->Output('collection_report.pdf', 'I');
   }
  }  

  $collectionForm = new printCollection();
  $collectionForm -> start_date = $_GET["start_date"];
  $collectionForm -> end_date = $_GET["end_date"];
  $collectionForm -> customercode = $_GET["customercode"];
  $collectionForm -> paymode = $_GET["paymode"];
  $collectionForm -> reptype = $_GET["reptype"];
  $collectionForm -> generatedby = $_GET["generatedby"];
  $collectionForm -> getCollectionDetails();
?>